server:
  port: 8888
spring:
  application:
    name: myBlog
  redis:
    host: localhost
    port: 6379
  #数据库配置
#datasource
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_test?characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mappering/*.xml
#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath:/mappering/*.xml


